ALTER TABLE "CompanySetting" ADD COLUMN IF NOT EXISTS "smtpHost" TEXT;
ALTER TABLE "CompanySetting" ADD COLUMN IF NOT EXISTS "smtpPort" INTEGER DEFAULT 587;
ALTER TABLE "CompanySetting" ADD COLUMN IF NOT EXISTS "smtpUser" TEXT;
ALTER TABLE "CompanySetting" ADD COLUMN IF NOT EXISTS "smtpPass" TEXT;
ALTER TABLE "CompanySetting" ADD COLUMN IF NOT EXISTS "smtpFrom" TEXT;
